name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  pack_and_push:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.5  

    - name: Build Source Generator
      run: dotnet pack WoWCombatLogParser.SourceGenerator -p:PackageVersion=$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")) -c Release --output .
      
    - name: Build Parser
      run: dotnet pack WoWCombatLogParser -p:PackageVersion=$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")) -c Release --output .
      
    - name: Publish Package
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
