name: Publish Package

on:
  push:
    branches: [ "main " ]    
  workflow_dispatch:    

permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  pack_and_push:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.5
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Set PACKAGE_VERSION variable
      run: echo "PACKAGE_VERSION=$(date +'%Y.%-m.%-d').${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build WoWCombatLogParser --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack WoWCombatLogParser --configuration Release /p:Version=${{ env.PACKAGE_VERSION }} --no-build --output .
    
    - name: Publish Package
      run: nuget push WoWCombatLogParser.${{ env.PACKAGE_VERSION }}.nupkg -Source 'https://nuget.pkg.github.com/Seriousnes/index.json' -ApiKey '${{ secrets.GITHUB_TOKEN }}'
