name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.5  
  
    - name: build
      run: dotnet build -c Release
      
    - name: pack WoWCombatLogParser
      run: dotnet pack WoWCombatLogParser -p:PackageVersion=$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")) -c Release --output .\packages --no-build

    - name: pack WoWCombatLogParser.SourceGenerator
      run: dotnet pack WoWCombatLogParser.SourceGenerator -p:PackageVersion=$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")) -c Release --output .\packages --no-build  
  
    - name: authenticate
      run: dotnet nuget add source --username Seriousnes --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Seriousnes/index.json"
    
    - name: publish
      run: dotnet nuget push .\packages\*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -s "github"
