name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]      

permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  pack_and_push:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.5   
        
    - name: Build
      run: dotnet pack WoWCombatLogParser -p:PackageVersion=$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")) --configuration Release --output .
      
    - name: Publish Package
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --sources "github"
